"""Independent TIGER SID and generator joint-training method."""

from .data import (
    DynamicSidTemplate,
    JointTigerBatch,
    MaterializedSidBatch,
    SidTokenLayout,
    TigerJointDataError,
    materialize_dynamic_sid_batch,
)
from .training import (
    HuggingFaceCausalLMJointAdapter,
    JointGeneratorOutput,
    JointTigerLossOutput,
    JointTigerTrainingModule,
    causal_language_model_loss,
    compute_joint_tiger_loss,
    multi_positive_info_nce,
    teacher_forced_accuracy,
)
from .catalog import PoiCatalogError, PoiEmbeddingStore
from .dataset import (
    DATA_SCHEMA_VERSION,
    DYNAMIC_HISTORY_IDENTIFIER,
    DYNAMIC_TARGET_IDENTIFIER,
    HistoryWindow,
    SidFreeDataResult,
    TigerJointDatasetError,
    build_joint_special_tokens,
    build_sid_free_training_data,
    raw_order_to_sid_free_sample,
)
from .preparation import (
    DynamicTigerExample,
    TigerJointPreparationError,
    build_sid_token_layout,
    collate_dynamic_examples,
    load_fresh_tokenizer_and_template,
    load_dynamic_examples,
    load_dynamic_token_ids,
    parse_sid_free_record,
    parse_sid_free_records,
    tokenize_dynamic_record,
)
from .preflight import (
    DynamicPreflightTemplate,
    DynamicSplitPreflight,
    TigerJointPreflightError,
    combine_dynamic_preflight_splits,
    build_fresh_initialization_contract,
    scan_dynamic_preflight_split,
)

__all__ = [
    "DynamicSidTemplate",
    "DynamicPreflightTemplate",
    "DynamicSplitPreflight",
    "DynamicTigerExample",
    "HuggingFaceCausalLMJointAdapter",
    "JointGeneratorOutput",
    "JointTigerBatch",
    "JointTigerLossOutput",
    "JointTigerTrainingModule",
    "MaterializedSidBatch",
    "PoiCatalogError",
    "PoiEmbeddingStore",
    "SidTokenLayout",
    "TigerJointDataError",
    "TigerJointDatasetError",
    "TigerJointPreparationError",
    "TigerJointPreflightError",
    "DATA_SCHEMA_VERSION",
    "DYNAMIC_HISTORY_IDENTIFIER",
    "DYNAMIC_TARGET_IDENTIFIER",
    "HistoryWindow",
    "SidFreeDataResult",
    "build_fresh_initialization_contract",
    "build_joint_special_tokens",
    "build_sid_token_layout",
    "build_sid_free_training_data",
    "causal_language_model_loss",
    "compute_joint_tiger_loss",
    "combine_dynamic_preflight_splits",
    "collate_dynamic_examples",
    "load_fresh_tokenizer_and_template",
    "load_dynamic_examples",
    "load_dynamic_token_ids",
    "parse_sid_free_record",
    "parse_sid_free_records",
    "raw_order_to_sid_free_sample",
    "materialize_dynamic_sid_batch",
    "multi_positive_info_nce",
    "teacher_forced_accuracy",
    "scan_dynamic_preflight_split",
    "tokenize_dynamic_record",
]
