### model
model_name_or_path: models/Qwen3-0.6B-POI-Vocab-v1
trust_remote_code: false
resize_vocab: false

### method
stage: sft
do_train: true
do_eval: true
finetuning_type: full

### dataset
dataset: beijing_order_main_v1_train
eval_dataset: beijing_order_main_v1_valid
dataset_dir: configs/sft
tokenized_path: data/sft/tokenized/beijing_order_main_v1_qwen3_0.6b
template: qwen3_nothink
enable_thinking: false
cutoff_len: 128
packing: true
train_on_prompt: false
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output and checkpoints
output_dir: outputs/sft/qwen3_0.6b_main_v1
overwrite_output_dir: false
logging_strategy: steps
logging_steps: 20
logging_first_step: true
logging_dir: outputs/sft/qwen3_0.6b_main_v1/tensorboard
save_strategy: steps
save_steps: 0.5
save_total_limit: 2
save_only_model: false
save_safetensors: true
plot_loss: true
report_to: tensorboard

### train
num_train_epochs: 1.0
per_device_train_batch_size: 64
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
optim: adamw_torch
weight_decay: 0.01
lr_scheduler_type: cosine
warmup_ratio: 0.03
max_grad_norm: 1.0
bf16: true
fp16: false
seed: 42
data_seed: 42
gradient_checkpointing: true
disable_gradient_checkpointing: false
include_tokens_per_second: true
include_num_input_tokens_seen: true
skip_memory_metrics: false
resume_from_checkpoint: null

### validation
per_device_eval_batch_size: 64
eval_strategy: steps
eval_steps: 0.5
load_best_model_at_end: false
predict_with_generate: false
compute_accuracy: false
